// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhfhqlrtofmykbbdvcaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoZmhxbHJ0b2ZteWtiYmR2Y2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzUyODUsImV4cCI6MjA3NDYxMTI4NX0.q0bBiglFshDqr5VpouHkuF2CDggh-j2TWJAiJeizWw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});